substitutions:
  name: sonoff-rfbridge
  friendly_name: Sonoff RF Bridge
esphome:
  name: $name
  comment: Sonoff RF Bridge
  name_add_mac_suffix: true

  # This will allow for (future) project identification,
  # configuration and updates.
  project:
    name: cpyarger.sonoff-rfbridge
    version: "1.0"
esp8266:
  board: esp01_1m
dashboard_import:
  package_import_url: github://cpyarger/esphome-templates/sonoff-rfbridge.yaml@main

wifi:
  # Set up a wifi access point
  ap:
    password: "12345678"
captive_portal:
web_server:
  port: 80
ota:
api:
uart:
  tx_pin: 1
  rx_pin: 3
  baud_rate: 19200
logger:
  baud_rate: 0
rf_bridge:
  on_code_received:
    then:
    # Simple method for receiving codes in home assistant
      - homeassistant.tag_scanned: !lambda |-
          return esphome::to_string(data.code) ;
sensor:
  - platform: wifi_signal
    name: RF Bridge WIFI Signal
    update_interval: 120s
  - platform: uptime
    name: Bridge Uptime
    update_interval: 120s