substitutions:
  name: sonoff-tx-t1
  friendly_name: Sonoff TX T1
esphome:
  name: $name
  comment: Sonoff TX T1
  name_add_mac_suffix: true

  # This will allow for (future) project identification,
  # configuration and updates.
  project:
    name: esphome.sonoff-tx-t1
    version: "1.0"
esp8266:
  board: esp01_1m
# Enable logging
logger:
# Enable Home Assistant API
api:
ota:
# This should point to the public location of this yaml file.
dashboard_import:
  package_import_url: github://cpyarger/esphome-templates/sonoff-tx-t1.yaml@main

wifi:
  # Set up a wifi access point
  ap:
    password: "12345678"
captive_portal:
# Sets up the improv via serial client for Wi-Fi provisioning
improv_serial:
web_server:
  port: 80
binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    id: button_1
    on_press:
      then:
        - light.toggle: light_1
  - platform: status
    name: "$friendly_name Status"
output:
  - platform: gpio
    pin: GPIO12
    id: relay_1
light:
  - platform: binary
    name: "$friendly_name Light 1"
    id: light_1
    output: relay_1
status_led:
  pin:
    number: GPIO13
    inverted: yes