substitutions:
  name: sonoff-th16-si7021
  friendly_name: Sonoff TH16
esphome:
  name: $name
  comment: Sonoff TH16
  name_add_mac_suffix: true

  # This will allow for (future) project identification,
  # configuration and updates.
  project:
    name: esphome.sonoff-th16-si7021
    version: "1.0"
esp8266:
  board: esp01_1m
dashboard_import:
  package_import_url: github://cpyarger/esphome-templates/sonoff-th16-si7021.yaml@main

wifi:
  # Set up a wifi access point
  ap:
    password: "12345678"
# Sets up the improv via serial client for Wi-Fi provisioning
improv_serial:
captive_portal:
web_server:
  port: 80
# Enable logging
logger:
# Enable Home Assistant API
api:
ota:
status_led:
  pin:
    number: GPIO13
    inverted: True
binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "Button"
  - platform: status
    name: "${friendly_name} Status"
output:
  - platform: gpio
    id: output_1
    pin: GPIO12
fan:
  - platform: binary
    output: output_1
    name: "${friendly_name} Fan"
sensor:
  - platform: dht
    model: Si7021
    pin: GPIO14
    update_interval: 1s
    temperature:
      name: "$friendly_name Temperature"
      # used to set automatic on/off of based on the temperature in C
      #on_value_range:
      #  - above: 26.0
      #    then:
      #      - output.turn_on: output_1
      #  - below: 21.2
      #    then:
      #      - output.turn_off: output_1
    humidity:
      name: "$friendly_name Humidity"
      #on_value_range:
      #  - above: 80.0
      #    then:
      #      - output.turn_on: output_1
      #  - below: 80.0
      #    then:
      #      - output.turn_off: output_1