name: CI

on:
  pull_request:

jobs:
  ci:
    name: Building ${{ matrix.file }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        file:
          - esp32-gateway-ethernet.yaml
          - esp32-gateway-wifi.yaml
          - shelly-1.yaml
          - sonoff-basic.yaml
          - sonoff-ifan04-l.yaml
          - sonoff-rfbridge.yaml
          - sonoff-tx-t1.yaml
          - sonoff-tx-t2.yaml
          - sonoff-tx-t3.yaml
          - sp501e.yaml
          - ttgo-higrow-stick.yaml
          - wyze-plug.yaml
          - sonoff-th16-si7021.yaml
          - shelly-uni-doorbell.yaml
          - emporia-vue2.yaml
          - emporia-vue2-3-phase.yaml
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Build ESPHome firmware to verify configuration
        uses: esphome/build-action@v1.3.1
        with:
          yaml_file: ${{ matrix.file }}
